### ISSUE TITLE
go.mod改一下吧

### ISSUE THREAD

**Issue by chennqqi** [igufei/gin-proxy#1]
1.13之后要求路径中有点
```Go
module gin-proxy
```
修改为:
```Go
module github.com/igufei/gin-proxy
```

**Comment by igufei** [comment]
感谢反馈






| |
顾飞
保洁总监
|
|
江苏爱谷飞网络科技有限公司
igufei@126.com
|
签名由网易邮箱大师定制
在2020年5月18日 10:26，chennqqi<notifications@github.com> 写道：

1.13之后要求路径中有点

modulegin-proxy

修改为:

modulegithub.com/igufei/gin-proxy
